parameters:
#    devilcius_sdd_generator.example.class: devilcius\SDDGeneratorBundle\Example

services:
#    devilcius_sdd_generator.example:
#        class: %devilcius_sdd_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
