<?php

namespace devilcius\SDDGeneratorBundle\Tests\Lib;

use devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-27 at 16:52:05.
 */
class SEPADirectDebitTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SEPADirectDebitTransaction
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SEPADirectDebitTransaction;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::getInstructionIdentification
     * @todo   Implement testGetInstructionIdentification().
     */
    public function testGetInstructionIdentification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::setInstructionIdentification
     * @todo   Implement testSetInstructionIdentification().
     */
    public function testSetInstructionIdentification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::getEndToEndIdentification
     * @todo   Implement testGetEndToEndIdentification().
     */
    public function testGetEndToEndIdentification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::setEndToEndIdentification
     * @todo   Implement testSetEndToEndIdentification().
     */
    public function testSetEndToEndIdentification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::getInstructedAmount
     * @todo   Implement testGetInstructedAmount().
     */
    public function testGetInstructedAmount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::setInstructedAmount
     * @todo   Implement testSetInstructedAmount().
     */
    public function testSetInstructedAmount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::getMandateIdentification
     * @todo   Implement testGetMandateIdentification().
     */
    public function testGetMandateIdentification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::setMandateIdentification
     * @todo   Implement testSetMandateIdentification().
     */
    public function testSetMandateIdentification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::getDateOfSignature
     * @todo   Implement testGetDateOfSignature().
     */
    public function testGetDateOfSignature()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::setDateOfSignature
     * @todo   Implement testSetDateOfSignature().
     */
    public function testSetDateOfSignature()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::getAmendmentIndicator
     * @todo   Implement testGetAmendmentIndicator().
     */
    public function testGetAmendmentIndicator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::setAmendmentIndicator
     * @todo   Implement testSetAmendmentIndicator().
     */
    public function testSetAmendmentIndicator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::getDebtorAgentBIC
     * @todo   Implement testGetDebtorAgentBIC().
     */
    public function testGetDebtorAgentBIC()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::setDebtorAgentBIC
     * @todo   Implement testSetDebtorAgentBIC().
     */
    public function testSetDebtorAgentBIC()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::getDebtorName
     * @todo   Implement testGetDebtorName().
     */
    public function testGetDebtorName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::setDebtorName
     * @todo   Implement testSetDebtorName().
     */
    public function testSetDebtorName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::getDebtorIBAN
     * @todo   Implement testGetDebtorIBAN().
     */
    public function testGetDebtorIBAN()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::setDebtorIBAN
     * @todo   Implement testSetDebtorIBAN().
     */
    public function testSetDebtorIBAN()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::getRemittanceInformation
     * @todo   Implement testGetRemittanceInformation().
     */
    public function testGetRemittanceInformation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::setRemittanceInformation
     * @todo   Implement testSetRemittanceInformation().
     */
    public function testSetRemittanceInformation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers devilcius\SDDGeneratorBundle\Lib\SEPADirectDebitTransaction::getXmlDirectDebitTransaction
     * @todo   Implement testGetXmlDirectDebitTransaction().
     */
    public function testGetXmlDirectDebitTransaction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
